In [32]:
"""
The first step in this project is to enhance the dataset. From each twit, 
I want the extract the name of the financial security and append it to another column.
"""

'\nThe first step in this project is to enhance the dataset. From each twit, \nI want the extract the name of the financial security and append it to another column.\n'

In [197]:
import pandas as pd
import numpy as np
import re
import requests
from bs4 import BeautifulSoup
from alpha_vantage.timeseries import TimeSeries
from alpha_vantage.techindicators import TechIndicators
from matplotlib.pyplot import figure
import matplotlib.pyplot as plt
import os
from dotenv import load_dotenv
load_dotenv()

In [144]:
df = pd.read_csv("../INPUT/stock_data.csv")

In [145]:
display(df)

                                                   Text  Sentiment
0     Kickers on my watchlist XIDE TIT SOQ PNK CPW B...          1
1     user: AAP MOVIE. 55% return for the FEA/GEED i...          1
2     user I'd be afraid to short AMZN - they are lo...          1
3                                     MNTA Over 12.00            1
4                                      OI  Over 21.37            1
...                                                 ...        ...
5786  Industry body CII said #discoms are likely to ...         -1
5787  #Gold prices slip below Rs 46,000 as #investor...         -1
5788  Workers at Bajaj Auto have agreed to a 10% wag...          1
5789  #Sharemarket LIVE: Sensex off day’s high, up 6...          1
5790  #Sensex, #Nifty climb off day's highs, still u...          1

[5791 rows x 2 columns]

In [146]:
# Checking to see if the dataset needs any cleaning, but it doesn't:
print(df.isnull().sum())
print(df.duplicated().sum())

Text         0
Sentiment    0
dtype: int64
0

In [95]:
# Web scraping to get the symbols for all the stocks on the S&P500
res = requests.get("https://en.wikipedia.org/wiki/List_of_S%26P_500_companies").text
soup = BeautifulSoup(res)
sp500 = []
for n in range(2, 506):
    sp_ticker = soup.select(f"#constituents > tbody > tr:nth-child({n}) > td:nth-child(1) > a")[0].text
    sp500.append(sp_ticker)

In [96]:
print(sp500)

['MMM', 'ABT', 'ABBV', 'ABMD', 'ACN', 'ATVI', 'ADBE', 'AMD', 'AAP', 'AES', 'AFL', 'A', 'APD', 'AKAM', 'ALK', 'ALB', 'ARE', 'ALXN', 'ALGN', 'ALLE', 'ADS', 'LNT', 'ALL', 'GOOGL', 'GOOG', 'MO', 'AMZN', 'AMCR', 'AEE', 'AAL', 'AEP', 'AXP', 'AIG', 'AMT', 'AWK', 'AMP', 'ABC', 'AME', 'AMGN', 'APH', 'ADI', 'ANSS', 'ANTM', 'AON', 'AOS', 'APA', 'AIV', 'AAPL', 'AMAT', 'APTV', 'ADM', 'ANET', 'AJG', 'AIZ', 'T', 'ATO', 'ADSK', 'ADP', 'AZO', 'AVB', 'AVY', 'BKR', 'BLL', 'BAC', 'BK', 'BAX', 'BDX', 'BRK.B', 'BBY', 'BIIB', 'BLK', 'BA', 'BKNG', 'BWA', 'BXP', 'BSX', 'BMY', 'AVGO', 'BR', 'BF.B', 'CHRW', 'COG', 'CDNS', 'CPB', 'COF', 'CAH', 'KMX', 'CCL', 'CARR', 'CAT', 'CBOE', 'CBRE', 'CDW', 'CE', 'CNC', 'CNP', 'CTL', 'CERN', 'CF', 'SCHW', 'CHTR', 'CVX', 'CMG', 'CB', 'CHD', 'CI', 'CINF', 'CTAS', 'CSCO', 'C', 'CFG', 'CTXS', 'CLX', 'CME', 'CMS', 'KO', 'CTSH', 'CL', 'CMCSA', 'CMA', 'CAG', 'CXO', 'COP', 'ED', 'STZ', 'COO', 'CPRT', 'GLW', 'CTVA', 'COST', 'COTY', 'CCI', 'CSX', 'CMI', 'CVS', 'DHI', 'DHR', 'DRI', 'DVA', 'DE', 'DAL', 'XRAY', 'DVN', 'DXCM', 'FANG', 'DLR', 'DFS', 'DISCA', 'DISCK', 'DISH', 'DG', 'DLTR', 'D', 'DPZ', 'DOV', 'DOW', 'DTE', 'DUK', 'DRE', 'DD', 'DXC', 'ETFC', 'EMN', 'ETN', 'EBAY', 'ECL', 'EIX', 'EW', 'EA', 'EMR', 'ETR', 'EOG', 'EFX', 'EQIX', 'EQR', 'ESS', 'EL', 'EVRG', 'ES', 'RE', 'EXC', 'EXPE', 'EXPD', 'EXR', 'XOM', 'FFIV', 'FB', 'FAST', 'FRT', 'FDX', 'FIS', 'FITB', 'FE', 'FRC', 'FISV', 'FLT', 'FLIR', 'FLS', 'FMC', 'F', 'FTNT', 'FTV', 'FBHS', 'FOXA', 'FOX', 'BEN', 'FCX', 'GPS', 'GRMN', 'IT', 'GD', 'GE', 'GIS', 'GM', 'GPC', 'GILD', 'GL', 'GPN', 'GS', 'GWW', 'HRB', 'HAL', 'HBI', 'HOG', 'HIG', 'HAS', 'HCA', 'PEAK', 'HSIC', 'HSY', 'HES', 'HPE', 'HLT', 'HFC', 'HOLX', 'HD', 'HON', 'HRL', 'HST', 'HWM', 'HPQ', 'HUM', 'HBAN', 'HII', 'IEX', 'IDXX', 'INFO', 'ITW', 'ILMN', 'INCY', 'IR', 'INTC', 'ICE', 'IBM', 'IP', 'IPG', 'IFF', 'INTU', 'ISRG', 'IVZ', 'IPGP', 'IQV', 'IRM', 'JKHY', 'J', 'JBHT', 'SJM', 'JNJ', 'JCI', 'JPM', 'JNPR', 'KSU', 'K', 'KEY', 'KEYS', 'KMB', 'KIM', 'KMI', 'KLAC', 'KSS', 'KHC', 'KR', 'LB', 'LHX', 'LH', 'LRCX', 'LW', 'LVS', 'LEG', 'LDOS', 'LEN', 'LLY', 'LNC', 'LIN', 'LYV', 'LKQ', 'LMT', 'L', 'LOW', 'LYB', 'MTB', 'MRO', 'MPC', 'MKTX', 'MAR', 'MMC', 'MLM', 'MAS', 'MA', 'MKC', 'MXIM', 'MCD', 'MCK', 'MDT', 'MRK', 'MET', 'MTD', 'MGM', 'MCHP', 'MU', 'MSFT', 'MAA', 'MHK', 'TAP', 'MDLZ', 'MNST', 'MCO', 'MS', 'MOS', 'MSI', 'MSCI', 'MYL', 'NDAQ', 'NOV', 'NTAP', 'NFLX', 'NWL', 'NEM', 'NWSA', 'NWS', 'NEE', 'NLSN', 'NKE', 'NI', 'NBL', 'JWN', 'NSC', 'NTRS', 'NOC', 'NLOK', 'NCLH', 'NRG', 'NUE', 'NVDA', 'NVR', 'ORLY', 'OXY', 'ODFL', 'OMC', 'OKE', 'ORCL', 'OTIS', 'PCAR', 'PKG', 'PH', 'PAYX', 'PAYC', 'PYPL', 'PNR', 'PBCT', 'PEP', 'PKI', 'PRGO', 'PFE', 'PM', 'PSX', 'PNW', 'PXD', 'PNC', 'PPG', 'PPL', 'PFG', 'PG', 'PGR', 'PLD', 'PRU', 'PEG', 'PSA', 'PHM', 'PVH', 'QRVO', 'PWR', 'QCOM', 'DGX', 'RL', 'RJF', 'RTX', 'O', 'REG', 'REGN', 'RF', 'RSG', 'RMD', 'RHI', 'ROK', 'ROL', 'ROP', 'ROST', 'RCL', 'SPGI', 'CRM', 'SBAC', 'SLB', 'STX', 'SEE', 'SRE', 'NOW', 'SHW', 'SPG', 'SWKS', 'SLG', 'SNA', 'SO', 'LUV', 'SWK', 'SBUX', 'STT', 'STE', 'SYK', 'SIVB', 'SYF', 'SNPS', 'SYY', 'TMUS', 'TROW', 'TTWO', 'TPR', 'TGT', 'TEL', 'FTI', 'TFX', 'TXN', 'TXT', 'TMO', 'TIF', 'TJX', 'TSCO', 'TT', 'TDG', 'TRV', 'TFC', 'TWTR', 'TSN', 'UDR', 'ULTA', 'USB', 'UAA', 'UA', 'UNP', 'UAL', 'UNH', 'UPS', 'URI', 'UHS', 'UNM', 'VFC', 'VLO', 'VAR', 'VTR', 'VRSN', 'VRSK', 'VZ', 'VRTX', 'VIAC', 'V', 'VNO', 'VMC', 'WRB', 'WAB', 'WMT', 'WBA', 'DIS', 'WM', 'WAT', 'WEC', 'WFC', 'WELL', 'WST', 'WDC', 'WU', 'WRK', 'WY', 'WHR', 'WMB', 'WLTW', 'WYNN', 'XEL', 'XRX', 'XLNX', 'XYL', 'YUM', 'ZBRA', 'ZBH', 'ZION']

In [192]:
"""
Now, I want to add another column to the data set, with the ticker or name of the security:
- Look for #
- Look for capitalized letters -- Compare to another sp500 (which is the list I got from web scraping the wikipedia page) 
"""

df["Ticker"] = 0  #Intializing column

for e in range(df["Text"].count()):
    final_list = []
    list_tickers = (re.findall(r'\b([A-Z]+[A-Z])\b', df["Text"][e]))

    for ticker in list_tickers:
        if ticker in sp500:
            final_list.append(ticker)
            df["Ticker"][e] = final_list[0]
    
    if len(final_list) == 0:
        df["Ticker"][e] = None
        
    


df.head(50)
df.isnull().sum()
df_clean = df.dropna()

df_clean


#def extractSecurity (text):

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

                                                   Text  Sentiment Ticker
1     user: AAP MOVIE. 55% return for the FEA/GEED i...          1    AAP
2     user I'd be afraid to short AMZN - they are lo...          1   AMZN
6     AAP - user if so then the current downtrend wi...         -1    AAP
7     Monday's relative weakness. NYX WIN TIE TAP IC...         -1    TAP
8     GOOG - ower trend line channel test & volume s...          1   GOOG
...                                                 ...        ...    ...
5649  Sensex Ends 693 Points Higher, Nifty Reclaims ...          1     IT
5650  Sensex closes 693 points higher, Nifty at 7,80...          1     IT
5684  Sensex jumps over 750 points to cross 29,000 m...          1     IT
5772  Sensex Opens 166 Points Lower, Nifty Starts Da...         -1     IT
5773  Sensex opens 166 points lower at 35,469, Nifty...         -1     IT

[2306 rows x 3 columns]

In [193]:
df_clean["Ticker"].value_counts()

AAP     834
BAC     188
GOOG    151
AMZN     93
GS       54
       ...
AVY       1
ABMD      1
SEE       1
PPG       1
ETN       1
Name: Ticker, Length: 183, dtype: int64

In [198]:
df_clean['Positive Sentiment']=df_clean['Sentiment'].replace(-1,0)
df_clean['Negative']=df_clean['Sentiment'].replace(1,0)
df_clean['Negative Sentiment']=df_clean['Negative'].replace(-1,1)


#Dropping of the temporary column 'Negative'
df_clean=df_clean.drop('Negative', axis=1)
#Dropping of the Sentiment column
df_clean=df_clean.drop('Sentiment', axis=1)
df_clean

,Text,Ticker,Positive Sentiment,Negative Sentiment
1,user: AAP MOVIE. 55% return for the FEA/GEED i...,AAP,1,0
2,user I'd be afraid to short AMZN - they are lo...,AMZN,1,0
6,AAP - user if so then the current downtrend wi...,AAP,0,1
7,Monday's relative weakness. NYX WIN TIE TAP IC...,TAP,0,1
8,GOOG - ower trend line channel test & volume s...,GOOG,1,0
...,...,...,...,...
5649,"Sensex Ends 693 Points Higher, Nifty Reclaims ...",IT,1,0
5650,"Sensex closes 693 points higher, Nifty at 7,80...",IT,1,0
5684,"Sensex jumps over 750 points to cross 29,000 m...",IT,1,0
5772,"Sensex Opens 166 Points Lower, Nifty Starts Da...",IT,0,1
5773,"Sensex opens 166 points lower at 35,469, Nifty...",IT,0,1

In [199]:
df_clean["Ticker"].value_counts()

AAP     834
BAC     188
GOOG    151
AMZN     93
GS       54
       ...
AVY       1
ABMD      1
SEE       1
PPG       1
ETN       1
Name: Ticker, Length: 183, dtype: int64

In [ ]:
key = os.getenv("ALPHAVANTAGE_APIKEY")